/**
 * Cloudflare R2 CDN helpers for Unique Detailing public assets.
 *
 * Heavy media lives on R2 under:
 *   assets/gallery/*   ← portfolio photos
 *   assets/services/*  ← PPF / product shots
 *   assets/marketing/* ← hero video, OG cover
 *   assets/unique-detailing-logo.png
 *
 * Responsive WebP variants are stored beside originals:
 *   foo.jpg → foo.w480.webp, foo.w768.webp, foo.w1080.webp, foo.w1440.webp
 *
 * Set VITE_CDN_URL (or VITE_ASSET_BASE_URL) to the public R2 base.
 * When unset, paths fall back to same-origin `/public` routes so local
 * development still works before R2 is populated.
 */

const RAW_CDN =
  (import.meta.env.VITE_CDN_URL as string | undefined) ||
  (import.meta.env.VITE_ASSET_BASE_URL as string | undefined) ||
  "";

export const CDN_BASE = RAW_CDN.replace(/\/$/, "");

/** Default responsive widths generated by scripts/optimize-r2-assets.mjs */
export const CDN_WIDTHS = [480, 768, 1080, 1440] as const;

/** Map a site-local public path to its R2 object key. */
export function toR2Key(path: string): string | null {
  const p = path.startsWith("/") ? path : `/${path}`;
  if (p.startsWith("/portfolio/")) return `assets/gallery/${p.slice("/portfolio/".length)}`;
  if (p.startsWith("/ppf/")) return `assets/services/${p.slice("/ppf/".length)}`;
  if (p === "/media/logo.png") return "assets/unique-detailing-logo.png";
  if (p === "/media/numberplate-logo.png") return "assets/unique-detailing-numberplate-logo.png";
  if (p === "/media/hero.mp4" || p === "/media/hero.mov") return "assets/marketing/hero.mp4";
  if (p === "/media/hero-poster.jpg") return "assets/marketing/hero-poster.jpg";
  if (p === "/og-cover.jpg" || p === "/og-share-1200.jpg") {
    return p === "/og-share-1200.jpg"
      ? "assets/marketing/og-share-1200.jpg"
      : "assets/marketing/og-cover.jpg";
  }
  if (p.startsWith("/media/")) return `assets/marketing/${p.slice("/media/".length)}`;
  return null;
}

/**
 * Resolve a media URL.
 * - Absolute http(s) URLs are returned unchanged.
 * - Known public paths are rewritten to the R2 CDN when configured.
 * - Unknown relative paths stay same-origin.
 */
export function cdn(path: string | undefined | null): string {
  if (!path) return "";
  if (/^https?:\/\//i.test(path)) return path;
  const key = toR2Key(path);
  if (CDN_BASE && key) return `${CDN_BASE}/${key}`;
  return path.startsWith("/") ? path : `/${path}`;
}

/** Absolute CDN/original URL for any local path or already-absolute URL. */
export function cdnUrl(pathOrUrl: string | undefined | null): string {
  return cdn(pathOrUrl);
}

/**
 * Responsive WebP variant URL for a local path or absolute CDN URL.
 * `foo.jpg` → `foo.w1080.webp`
 */
export function cdnWidth(pathOrUrl: string, width: number): string {
  const url = cdnUrl(pathOrUrl);
  if (!url) return "";
  return url.replace(/\.(jpe?g|png|webp)(\?.*)?$/i, `.w${width}.webp$2`);
}

/** `srcSet` string of WebP variants for `<source type="image/webp">` or `<img>`. */
export function cdnSrcSet(
  pathOrUrl: string,
  widths: readonly number[] = CDN_WIDTHS,
): string {
  return widths.map((w) => `${cdnWidth(pathOrUrl, w)} ${w}w`).join(", ");
}

/** Best single-size WebP for CSS backgrounds / simple `<img src>`. */
export function cdnSized(pathOrUrl: string, width = 1080): string {
  return cdnWidth(pathOrUrl, width) || cdnUrl(pathOrUrl);
}

export const LOGO_URL =
  (import.meta.env.VITE_LOGO_URL as string | undefined) ||
  cdn("/media/logo.png") ||
  "/media/logo.png";

export const OPS_URL =
  (import.meta.env.VITE_OPS_URL as string | undefined) || "https://ops.uniquedetailing.ru";

export const CONTACT_EMAIL =
  (import.meta.env.VITE_CONTACT_EMAIL as string | undefined) || "info@uniquedetailing.ru";
