/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UslugiRouteImport } from './routes/uslugi'
import { Route as SoglasieRouteImport } from './routes/soglasie'
import { Route as RabotyRouteImport } from './routes/raboty'
import { Route as PrivilegiiRouteImport } from './routes/privilegii'
import { Route as PolitikaRouteImport } from './routes/politika'
import { Route as PlenkaRouteImport } from './routes/plenka'
import { Route as NasledieRouteImport } from './routes/nasledie'
import { Route as KontaktyRouteImport } from './routes/kontakty'
import { Route as KompleksyRouteImport } from './routes/kompleksy'
import { Route as KlubRouteImport } from './routes/klub'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UslugiIndexRouteImport } from './routes/uslugi.index'
import { Route as RabotyIndexRouteImport } from './routes/raboty.index'
import { Route as UslugiSlugRouteImport } from './routes/uslugi.$slug'
import { Route as RabotySlugRouteImport } from './routes/raboty.$slug'
import { Route as ApiLeadRouteImport } from './routes/api.lead'

const UslugiRoute = UslugiRouteImport.update({
  id: '/uslugi',
  path: '/uslugi',
  getParentRoute: () => rootRouteImport,
} as any)
const SoglasieRoute = SoglasieRouteImport.update({
  id: '/soglasie',
  path: '/soglasie',
  getParentRoute: () => rootRouteImport,
} as any)
const RabotyRoute = RabotyRouteImport.update({
  id: '/raboty',
  path: '/raboty',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivilegiiRoute = PrivilegiiRouteImport.update({
  id: '/privilegii',
  path: '/privilegii',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitikaRoute = PolitikaRouteImport.update({
  id: '/politika',
  path: '/politika',
  getParentRoute: () => rootRouteImport,
} as any)
const PlenkaRoute = PlenkaRouteImport.update({
  id: '/plenka',
  path: '/plenka',
  getParentRoute: () => rootRouteImport,
} as any)
const NasledieRoute = NasledieRouteImport.update({
  id: '/nasledie',
  path: '/nasledie',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktyRoute = KontaktyRouteImport.update({
  id: '/kontakty',
  path: '/kontakty',
  getParentRoute: () => rootRouteImport,
} as any)
const KompleksyRoute = KompleksyRouteImport.update({
  id: '/kompleksy',
  path: '/kompleksy',
  getParentRoute: () => rootRouteImport,
} as any)
const KlubRoute = KlubRouteImport.update({
  id: '/klub',
  path: '/klub',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UslugiIndexRoute = UslugiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UslugiRoute,
} as any)
const RabotyIndexRoute = RabotyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RabotyRoute,
} as any)
const UslugiSlugRoute = UslugiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => UslugiRoute,
} as any)
const RabotySlugRoute = RabotySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => RabotyRoute,
} as any)
const ApiLeadRoute = ApiLeadRouteImport.update({
  id: '/api/lead',
  path: '/api/lead',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/klub': typeof KlubRoute
  '/kompleksy': typeof KompleksyRoute
  '/kontakty': typeof KontaktyRoute
  '/nasledie': typeof NasledieRoute
  '/plenka': typeof PlenkaRoute
  '/politika': typeof PolitikaRoute
  '/privilegii': typeof PrivilegiiRoute
  '/raboty': typeof RabotyRouteWithChildren
  '/soglasie': typeof SoglasieRoute
  '/uslugi': typeof UslugiRouteWithChildren
  '/api/lead': typeof ApiLeadRoute
  '/raboty/$slug': typeof RabotySlugRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/raboty/': typeof RabotyIndexRoute
  '/uslugi/': typeof UslugiIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/klub': typeof KlubRoute
  '/kompleksy': typeof KompleksyRoute
  '/kontakty': typeof KontaktyRoute
  '/nasledie': typeof NasledieRoute
  '/plenka': typeof PlenkaRoute
  '/politika': typeof PolitikaRoute
  '/privilegii': typeof PrivilegiiRoute
  '/soglasie': typeof SoglasieRoute
  '/api/lead': typeof ApiLeadRoute
  '/raboty/$slug': typeof RabotySlugRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/raboty': typeof RabotyIndexRoute
  '/uslugi': typeof UslugiIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/klub': typeof KlubRoute
  '/kompleksy': typeof KompleksyRoute
  '/kontakty': typeof KontaktyRoute
  '/nasledie': typeof NasledieRoute
  '/plenka': typeof PlenkaRoute
  '/politika': typeof PolitikaRoute
  '/privilegii': typeof PrivilegiiRoute
  '/raboty': typeof RabotyRouteWithChildren
  '/soglasie': typeof SoglasieRoute
  '/uslugi': typeof UslugiRouteWithChildren
  '/api/lead': typeof ApiLeadRoute
  '/raboty/$slug': typeof RabotySlugRoute
  '/uslugi/$slug': typeof UslugiSlugRoute
  '/raboty/': typeof RabotyIndexRoute
  '/uslugi/': typeof UslugiIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/klub'
    | '/kompleksy'
    | '/kontakty'
    | '/nasledie'
    | '/plenka'
    | '/politika'
    | '/privilegii'
    | '/raboty'
    | '/soglasie'
    | '/uslugi'
    | '/api/lead'
    | '/raboty/$slug'
    | '/uslugi/$slug'
    | '/raboty/'
    | '/uslugi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/klub'
    | '/kompleksy'
    | '/kontakty'
    | '/nasledie'
    | '/plenka'
    | '/politika'
    | '/privilegii'
    | '/soglasie'
    | '/api/lead'
    | '/raboty/$slug'
    | '/uslugi/$slug'
    | '/raboty'
    | '/uslugi'
  id:
    | '__root__'
    | '/'
    | '/klub'
    | '/kompleksy'
    | '/kontakty'
    | '/nasledie'
    | '/plenka'
    | '/politika'
    | '/privilegii'
    | '/raboty'
    | '/soglasie'
    | '/uslugi'
    | '/api/lead'
    | '/raboty/$slug'
    | '/uslugi/$slug'
    | '/raboty/'
    | '/uslugi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KlubRoute: typeof KlubRoute
  KompleksyRoute: typeof KompleksyRoute
  KontaktyRoute: typeof KontaktyRoute
  NasledieRoute: typeof NasledieRoute
  PlenkaRoute: typeof PlenkaRoute
  PolitikaRoute: typeof PolitikaRoute
  PrivilegiiRoute: typeof PrivilegiiRoute
  RabotyRoute: typeof RabotyRouteWithChildren
  SoglasieRoute: typeof SoglasieRoute
  UslugiRoute: typeof UslugiRouteWithChildren
  ApiLeadRoute: typeof ApiLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uslugi': {
      id: '/uslugi'
      path: '/uslugi'
      fullPath: '/uslugi'
      preLoaderRoute: typeof UslugiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/soglasie': {
      id: '/soglasie'
      path: '/soglasie'
      fullPath: '/soglasie'
      preLoaderRoute: typeof SoglasieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/raboty': {
      id: '/raboty'
      path: '/raboty'
      fullPath: '/raboty'
      preLoaderRoute: typeof RabotyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privilegii': {
      id: '/privilegii'
      path: '/privilegii'
      fullPath: '/privilegii'
      preLoaderRoute: typeof PrivilegiiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politika': {
      id: '/politika'
      path: '/politika'
      fullPath: '/politika'
      preLoaderRoute: typeof PolitikaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plenka': {
      id: '/plenka'
      path: '/plenka'
      fullPath: '/plenka'
      preLoaderRoute: typeof PlenkaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nasledie': {
      id: '/nasledie'
      path: '/nasledie'
      fullPath: '/nasledie'
      preLoaderRoute: typeof NasledieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakty': {
      id: '/kontakty'
      path: '/kontakty'
      fullPath: '/kontakty'
      preLoaderRoute: typeof KontaktyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kompleksy': {
      id: '/kompleksy'
      path: '/kompleksy'
      fullPath: '/kompleksy'
      preLoaderRoute: typeof KompleksyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/klub': {
      id: '/klub'
      path: '/klub'
      fullPath: '/klub'
      preLoaderRoute: typeof KlubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uslugi/': {
      id: '/uslugi/'
      path: '/'
      fullPath: '/uslugi/'
      preLoaderRoute: typeof UslugiIndexRouteImport
      parentRoute: typeof UslugiRoute
    }
    '/raboty/': {
      id: '/raboty/'
      path: '/'
      fullPath: '/raboty/'
      preLoaderRoute: typeof RabotyIndexRouteImport
      parentRoute: typeof RabotyRoute
    }
    '/uslugi/$slug': {
      id: '/uslugi/$slug'
      path: '/$slug'
      fullPath: '/uslugi/$slug'
      preLoaderRoute: typeof UslugiSlugRouteImport
      parentRoute: typeof UslugiRoute
    }
    '/raboty/$slug': {
      id: '/raboty/$slug'
      path: '/$slug'
      fullPath: '/raboty/$slug'
      preLoaderRoute: typeof RabotySlugRouteImport
      parentRoute: typeof RabotyRoute
    }
    '/api/lead': {
      id: '/api/lead'
      path: '/api/lead'
      fullPath: '/api/lead'
      preLoaderRoute: typeof ApiLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RabotyRouteChildren {
  RabotySlugRoute: typeof RabotySlugRoute
  RabotyIndexRoute: typeof RabotyIndexRoute
}

const RabotyRouteChildren: RabotyRouteChildren = {
  RabotySlugRoute: RabotySlugRoute,
  RabotyIndexRoute: RabotyIndexRoute,
}

const RabotyRouteWithChildren =
  RabotyRoute._addFileChildren(RabotyRouteChildren)

interface UslugiRouteChildren {
  UslugiSlugRoute: typeof UslugiSlugRoute
  UslugiIndexRoute: typeof UslugiIndexRoute
}

const UslugiRouteChildren: UslugiRouteChildren = {
  UslugiSlugRoute: UslugiSlugRoute,
  UslugiIndexRoute: UslugiIndexRoute,
}

const UslugiRouteWithChildren =
  UslugiRoute._addFileChildren(UslugiRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KlubRoute: KlubRoute,
  KompleksyRoute: KompleksyRoute,
  KontaktyRoute: KontaktyRoute,
  NasledieRoute: NasledieRoute,
  PlenkaRoute: PlenkaRoute,
  PolitikaRoute: PolitikaRoute,
  PrivilegiiRoute: PrivilegiiRoute,
  RabotyRoute: RabotyRouteWithChildren,
  SoglasieRoute: SoglasieRoute,
  UslugiRoute: UslugiRouteWithChildren,
  ApiLeadRoute: ApiLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
